# Determinan matriks
ordo matriksnya harus sama

-determinana dari matriks identitas adalah satu secara keseluruhan

-merubah baris akan mempengaruhi tanda dari determinan

-jika matriks ada baris/kolom yang merupakan 2x dari baris/kolom yang lain determinannya adalah 0

-matriks yang merupakan kelipatan dari matriks lain maka determinan dari matriks kelipatannya adalah:
kelipatan pangkat ordo di kali determinan matriks pertaman
misal determinan matriks pertama 3, maka determinan matriks ke 2 adalah 24
misal mat1=\

$$
\begin{bmatrix}
1 & 2\\
2 & 1
\end{bmatrix}
$$

determinan= 2\
dan mat 2 yang merupakan kelipatan 2x mat 1:

$$
\begin{bmatrix}
2 & 4\\
4 & 4
\end{bmatrix} determinan=12\
$$

rumusnya:\: $x^2dikali(determinan)$

-jika ada matriks yang barisnya merupakan kelipatan 2 dari baris matriks lain maka determinannya adalah 2x dari matrikx pertama:
misal determinan matrtiks ke 1 = 5, maka determinan matriks ke 2 adalah 10\
contoh:\
Misalkan kita punya matriks \

$$
𝐴=\begin{bmatrix}
3 & 4\\
2 & 1
\end{bmatrix}
$$

Maka determinan dari matriks =-5
Sekarang, jika kita gandakan baris pertama dari matriks

$$
𝐴2= \begin{bmatrix}
6 & 8\\
2 & 1
\end{bmatrix}
$$

dengan determinannya adalah -10
Ini menunjukkan bahwa ketika kita menggandakan baris pertama matriks
𝐴
A dengan faktor skalar (dalam hal ini 2), determinan dari matriks hasil
𝐴
A2
  menjadi dua kali lipat dari determinan matriks
𝐴
A2

-jika ada matriks yang kolomnya merupakan kelipatan 2 dari kolom matriks lain amaka determinannya adalah 4x dari matriks pertama:
misal determinan matriks 1 = 5 maka determinan matriks ke 2 = 20

-jika baris matriks merupakan hasil pengurangan dari determinan matriks lain maka baris matriksnya ke2 adalah hasil pengurangan dari baris matriks ke1:
misal\
mat1=\

$$
\begin{bmatrix}
3 & 4\\
2 & 1
\end{bmatrix}
$$

mat2=

$$
\begin{bmatrix}
4 & 7\\
2 & 1
\end{bmatrix}
$$

kolomnya pertama di tambahkan maka akan menjadi:\

$$
\begin{bmatrix}
1 & 3\\
2 & 1
\end{bmatrix}
$$

-jika metriks merupakan tipe matriks segitiga atas/bawah atau matriks diagonal makan determinan merupakan hasil kali dari diagonal utamanya

In [ ]:
import numpy as np

a = np.array([[1,0], [0,1]])
b = np.array([[1,0,0], [0,1,0],[0,0,1]])
c = np.array([[1,2,1],[3,1,2],[2,1,2]])
d = np.array([[3,1,2],[1,2,1],[2,1,2]])
e = np.array([[1,2,1],[2,4,2],[2,1,2]]) #baris 2 merupakan 2x baris 1 matriks d
f = np.array([[1,2,1],[2,4,2],[2,4,3]])
g = np.array([[6,2,4],[2,4,2],[4,2,4]]) #matriks ini merupakan 2x matriks d
h = np.array([[3,4],[2,1]])
i = np.array([[6,8],[4,2]])

k = np.array([[6,8],[2,1]])
j = np.array([[3,4],[2,1]])
l = np.array([[6,4],[4,1]])

z = np.array([[7,5],[2,1]])

x = np.array([[1,2,3],[0,1,4],[0,0,1]])
x1 = np.array([[1,0,0],[2,1,0],[2,1,2]])

x2= np.array([[1,2],[2,1]])
x3 = np.array([[2,4],[4,2]])

# print("Numpy Matrix is:")
# print(n_array)

det1 = np.linalg.det(x)
det = np.linalg.det(x1)

# print("\nDeterminant of given 3x3 matrix:")
print(float(det1))
print(float(det))

1.0
2.0


## formulasi bentuk determinan

In [ ]:
det11= [[3,2,3],
       [2,1,2],
       [4,2,1]]

kxjsk= np.linalg.det(det11)
print(kxjsk)

2.9999999999999996


In [ ]:
import numpy as np

# Definisikan matriks yang ingin diinvers
A = np.array([[3,1,3],
              [2,1,2],
              [4,2,1]])

# Cari invers dari matriks A
A_inverse = np.linalg.inv(A)

print("Matriks A:")
print(A)

print("\nInvers dari matriks A:")
print(A_inverse)


Matriks A:
[[3 1 3]
 [2 1 2]
 [4 2 1]]

Invers dari matriks A:
[[ 1.         -1.66666667  0.33333333]
 [-2.          3.         -0.        ]
 [ 0.          0.66666667 -0.33333333]]


## menghitung determinan dan invers metriks
menghitung invers matriks 5x5

###Tentukan Matriks dan Ordo:
Misalkan matriks yang diberikan adalah \( A \) dengan ordo \( 5 \times 5 \):
A=

$$
\begin{bmatrix}
1 & 0 & 4 & -6 & 3 \\
2 & 5 & 0 & 3 & 1 \\
-1 & 2 & 3 & 5 & -2 \\
2 & 1 & -2 & 3 & 0 \\
3 & -1 & 1 & 0 & 2
\end{bmatrix}
$$

###Kita akan menghitung determinan det(A) dengan menggunakan ekspansi kofaktor terhadap baris pertama. Rumusnya adalah:
$$
\det(A) = a_{11} C_{11} - a_{12} C_{12} + a_{13} C_{13} - a_{14} C_{14} + a_{15} C_{15}
$$

Di mana

$$
 a_{11}, a_{12}, a_{13}, a_{14}, a_{15}
$$

adalah elemen-elemen baris pertama matriks

$$
 A , dan C_{11}, C_{12}, C_{13}, C_{14}, C_{15}
$$

adalah kofaktor-kofaktor yang sesuai.


###Langkah-langkahnya adalah sebagai berikut:

1. **Tentukan Elemen dan Kofaktor:**

$$
   a_{11} = 1, a_{12} = 0, a_{13} = 4, a_{14} = -6, a_{15} = 3
$$

2. **Hitung Kofaktor

$$
C_{11}, C_{12}, C_{13}, C_{14}, C_{15}
$$

$$
   C_{11} = \det(M_{11})\\
   C_{12} = -\det(M_{12})\\
   C_{13} = \det(M_{13})\\
   C_{14} = -\det(M_{14})\\
   C_{15} = \det(M_{15})
$$

   di mana
   
   $$  M_{ij}
   $$
   
   adalah matriks minor dari A setelah menghapus baris pertama dan kolom ke-j

3. **Hitung Determinan Masing-masing Minor:**

$$
   M_{11} = \begin{bmatrix}
   5 & 0 & 3 & 1 \\
   2 & 3 & 5 & -2 \\
   1 & -2 & 3 & 0 \\
   -1 & 1 & 0 & 2
   \end{bmatrix}
$$
\
$$
   \det(M_{11}) = 5 \det\begin{bmatrix}
   3 & 5 & -2 \\
   -2 & 3 & 0 \\
   1 & 0 & 2 \\
   \end{bmatrix}- 0 + 3
$$
\
$$
  \det\begin{bmatrix}
   2 & 3 & -2 \\
   1 & -2 & 0 \\
   -1 & 1 & 2 \\
   \end{bmatrix} - 1
$$
\
$$   
   \det\begin{bmatrix}
   2 & 3 & 5 \\
   1 & -2 & 3 \\
   -1 & 1 & 0 \\
   \end{bmatrix}
$$
\
$$
   \det(M_{11}) = 5(-30) + 3(0) - (-16) = -150 + 0 + 16 = -134
$$
\
$$
   M_{12} = \begin{bmatrix}
   2 & 0 & 3 & 1 \\
   -1 & 3 & 5 & -2 \\
   2 & -2 & 3 & 0 \\
   3 & 1 & 0 & 2 \\
   \end{bmatrix}
$$
\
$$
   \det(M_{12}) = -(2 \det\begin{bmatrix}
   3 & 5 & -2 \\
   -2 & 3 & 0 \\
   1 & 0 & 2 \\
   \end{bmatrix}) = -(2 \times (-30)) = 60
$$
\
$$
   M_{13} = \begin{bmatrix}
   2 & 5 & 3 & 1 \\
   -1 & 2 & 5 & -2 \\
   2 & 1 & 3 & 0 \\
   3 & -1 & 0 & 2 \\
   \end{bmatrix}
$$
\
$$
   \det(M_{13}) = 2 \det\begin{bmatrix}
   2 & 3 & -2 \\
   1 & -2 & 0 \\
   -1 & 1 & 2 \\
   \end{bmatrix} - 5
$$
 \  
$$  
   \det\begin{bmatrix}
   -1 & 5 & -2 \\
   2 & 3 & 0 \\
   3 & 0 & 2 \\
   \end{bmatrix} + 3
$$
\
$$   
   \det\begin{bmatrix}
   -1 & 2 & -2 \\
   2 & 1 & 0 \\
   3 & -1 & 2 \\
   \end{bmatrix} - 1
$$   
\   
$$   
   \det\begin{bmatrix}
   -1 & 2 & 5 \\
   2 & 1 & 3 \\
   3 & -1 & 0 \\
   \end{bmatrix}
$$
\
$$
   \det(M_{13}) = 2(22) - 5(20) + 0 + 3(28) - (-16) = 44 - 100 + 84 + 16 = 44
$$
\
$$
   M_{14} = \begin{bmatrix}
   2 & 5 & 0 & 1 \\
   -1 & 2 & 3 & -2 \\
   2 & 1 & -2 & 0 \\
   3 & -1 & 1 & 2 \\
   \end{bmatrix} \)
$$
\
$$
   \det(M_{14}) = -(2 \det\begin{bmatrix}
   2 & 3 & -2 \\
   1 & -2 & 0 \\
   -1 & 1 & 2 \\
   \end{bmatrix}) = -(2 \times 6) = -12
$$
\
$$
   M_{15} = \begin{bmatrix}
   2 & 5 & 0 & 3 \\
   -1 & 2 & 3 & 5 \\
   2 & 1 & -2 & 3 \\
   3 & -1 & 1 & 0 \\
   \end{bmatrix} \)
$$
\
$$
   \det(M_{15}) = 2 \det\begin{bmatrix}
   2 & 3 & 5 \\
   1 & -2 & 3 \\
   -1 & 1 & 0 \\
   \end{bmatrix} - 5
$$
\
$$   
   \det\begin{bmatrix}
   -1 & 3 & 5 \\
   2 & -2 & 3 \\
   3 & 0 & 2 \\
   \end{bmatrix} + 0
$$   
\
$$   
   \det\begin{bmatrix}
   -1 & 2 & 5 \\
   2 & 1 & 3 \\
   3 & -1 & 0 \\
   \end{bmatrix} - 3
$$   
\  
$$   
   \det\begin{bmatrix}
   -1 & 2 & 3 \\
   2 & 1 & -2 \\
   3 & -1 & 1 \\
   \end{bmatrix}
$$
\
$$
   \det(M_{15}) = 2(22) - 5(20) + 0 - 3(-6) = 44 - 100 + 0 - 18 = -74
$$
\
4. **Hitung Determinan Utama:**
\
$$
\det(A) = (1)(-134) - (0)(60) + (4)(44) - (-6)(-12) + (3)(-74)
\det(A) = -134 + 0 + 176 - 72 - 222
\det(A) = -252
$$


In [ ]:
import numpy as np

def minor(matrix, i, j):
    # Menghapus baris ke-i dan kolom ke-j
    minor_matrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    return minor_matrix

def determinant(matrix):
    # Basis kasus untuk matriks 1x1
    if len(matrix) == 1:
        return matrix[0, 0]

    det = 0
    for j in range(matrix.shape[1]):
        # Menghitung kofaktor
        cofactor = ((-1) ** j) * matrix[0, j] * determinant(minor(matrix, 0, j))
        det += cofactor
    return det

# Matriks A
A = np.array([
    [1, 0, 4, -6, 3],
    [2, 5, 0, 3, 1],
    [-1, 2, 3, 5, -2],
    [2, 1, -2, 3, 0],
    [3, -1, 1, 0, 2]
])

# Menghitung determinan
det_A = determinant(A)
print(f"determinan {det_A}")


determinan 228


In [ ]:
import numpy as np

mat= np.mat([[1,4],
            [2,3]])

evalue, evect= np.linalg.eig(mat)

print('innnnni evalue',evalue)
print(evect)

innnnni evalue [-1.  5.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]
